### ISSUE TITLE
Olli simulator run on IBM Cloud

### ISSUE THREAD

**Issue by isc-rsingh** [AccessibleOlli/olli-sim#1]
- use `olli` space in @rajrsingh bluemix account
- try to use Cloudant db deployed there
- run route once only
- work started on `ibmcloud` branch

**Comment by isc-rsingh** [comment]
@vabarbosa could we skip the database and connect directly to the app via sockets? This is why I tentatively assigned you the client-side also.

**Comment by vabarbosa** [comment]
PR https://github.com/AccessibleOlli/olli-sim/pull/2
